### ISSUE TITLE
git permission denied

### ISSUE THREAD

**Issue by tutucea** [jdempcy/hdkit#4]
`git clone --recursive git@github.com:jdempcy/hdkit.git
Cloning into 'hdkit'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`
Can you please allow it to be downloaded as zip, whatever you proposed sounds super cool :)

p.s. I am not sure swisseph can calculate nodal crossing, can anyone explain or post a sample code on how to get this going ?  Thank you!!!

**Comment by jdempcy** [comment]
Is this issue still happening? I've gotten that error before when I had not set up SSH keys properly.

Also, can you clarify what you mean by nodal crossing? Do you mean the points where the Moon's orbit intersects with the ecliptic? That is the North and South Node and they can be calculated by Swiss Ephemeris. Just make sure to use True Node and not Mean Node. The True Nodes are the actual points while the Mean Nodes are averaged out and thus incorrect.

**Comment by jdempcy** [comment]
Closing as I cannot repro
